export const ROLES = Object.freeze({
  ADMIN: 'ADMIN',
  SYSTEM_ADMIN: 'SYSTEM_ADMIN',
  STUDENT_AFFAIRS_ADMIN: 'STUDENT_AFFAIRS_ADMIN',
  CLUB_MANAGER: 'CLUB_MANAGER',
  TREASURER: 'TREASURER',
  CLUB_MEMBER: 'CLUB_MEMBER',
})

import { vi } from '../locales/vi'

export const ROLE_LABELS = Object.freeze({
  [ROLES.ADMIN]: vi.roles.ADMIN,
  [ROLES.SYSTEM_ADMIN]: vi.roles.SYSTEM_ADMIN,
  [ROLES.STUDENT_AFFAIRS_ADMIN]: vi.roles.STUDENT_AFFAIRS_ADMIN,
  [ROLES.CLUB_MANAGER]: vi.roles.CLUB_MANAGER,
  [ROLES.TREASURER]: vi.roles.TREASURER,
  [ROLES.CLUB_MEMBER]: vi.roles.CLUB_MEMBER,
})

export function formatRole(role) {
  return ROLE_LABELS[role] || role || 'Khách'
}

export const PERMISSIONS = Object.freeze({
  VIEW_DASHBOARD: 'VIEW_DASHBOARD',
  VIEW_CLUBS: 'VIEW_CLUBS',
  REVIEW_CLUB_APPLICATIONS: 'REVIEW_CLUB_APPLICATIONS',
  MANAGE_CLUB_GOVERNANCE: 'MANAGE_CLUB_GOVERNANCE',
  APPLY_FOR_CLUB: 'APPLY_FOR_CLUB',
  JOIN_CLUB: 'JOIN_CLUB',
  VIEW_REPORTS: 'VIEW_REPORTS',
  VIEW_KPI: 'VIEW_KPI',
  AUTHOR_REPORTS: 'AUTHOR_REPORTS',
  REVIEW_REPORTS: 'REVIEW_REPORTS',
  VIEW_ACTIVITIES: 'VIEW_ACTIVITIES',
  MANAGE_ACTIVITIES: 'MANAGE_ACTIVITIES',
  PARTICIPATE_IN_ACTIVITIES: 'PARTICIPATE_IN_ACTIVITIES',
  VIEW_FINANCE: 'VIEW_FINANCE',
  MANAGE_FINANCE: 'MANAGE_FINANCE',
  REVIEW_FINANCE: 'REVIEW_FINANCE',
  VIEW_NOTIFICATIONS: 'VIEW_NOTIFICATIONS',
  VIEW_PROFILE: 'VIEW_PROFILE',
  MANAGE_USERS: 'MANAGE_USERS',
})

const ROLE_PERMISSIONS = Object.freeze({
  [ROLES.ADMIN]: new Set([
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_CLUBS,
    PERMISSIONS.REVIEW_CLUB_APPLICATIONS,
    PERMISSIONS.MANAGE_CLUB_GOVERNANCE,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.VIEW_KPI,
    PERMISSIONS.REVIEW_REPORTS,
    PERMISSIONS.VIEW_ACTIVITIES,
    PERMISSIONS.VIEW_FINANCE,
    PERMISSIONS.REVIEW_FINANCE,
    PERMISSIONS.VIEW_NOTIFICATIONS,
    PERMISSIONS.VIEW_PROFILE,
    PERMISSIONS.MANAGE_USERS,
  ]),
  [ROLES.SYSTEM_ADMIN]: new Set([
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_NOTIFICATIONS,
    PERMISSIONS.VIEW_PROFILE,
    PERMISSIONS.MANAGE_USERS,
  ]),
  [ROLES.STUDENT_AFFAIRS_ADMIN]: new Set([
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_CLUBS,
    PERMISSIONS.REVIEW_CLUB_APPLICATIONS,
    PERMISSIONS.MANAGE_CLUB_GOVERNANCE,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.VIEW_KPI,
    PERMISSIONS.REVIEW_REPORTS,
    PERMISSIONS.VIEW_ACTIVITIES,
    PERMISSIONS.VIEW_FINANCE,
    PERMISSIONS.REVIEW_FINANCE,
    PERMISSIONS.VIEW_NOTIFICATIONS,
    PERMISSIONS.VIEW_PROFILE,
  ]),
  [ROLES.CLUB_MANAGER]: new Set([
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_CLUBS,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.VIEW_ACTIVITIES,
    PERMISSIONS.VIEW_FINANCE,
    PERMISSIONS.VIEW_NOTIFICATIONS,
    PERMISSIONS.VIEW_PROFILE,
  ]),
  [ROLES.TREASURER]: new Set([
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_CLUBS,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.VIEW_ACTIVITIES,
    PERMISSIONS.VIEW_NOTIFICATIONS,
    PERMISSIONS.VIEW_PROFILE,
  ]),
  [ROLES.CLUB_MEMBER]: new Set([
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_CLUBS,
    PERMISSIONS.APPLY_FOR_CLUB,
    PERMISSIONS.JOIN_CLUB,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.VIEW_ACTIVITIES,
    PERMISSIONS.VIEW_NOTIFICATIONS,
    PERMISSIONS.VIEW_PROFILE,
  ]),
})

export function hasRolePermission(roles = [], permission) {
  return roles.some(role => ROLE_PERMISSIONS[role]?.has(permission))
}

export function hasPermission(user, clubAccess = [], permission) {
  const roles = user?.roles || []

  if (hasRolePermission(roles, permission)) {
    return true
  }

  if (permission === PERMISSIONS.AUTHOR_REPORTS) {
    return clubAccess.some(access => access.isManager || access.isTreasurer)
  }

  if (permission === PERMISSIONS.VIEW_KPI) {
    return clubAccess.some(access =>
      access.isApprovedMember || access.isManager || access.isTreasurer,
    )
  }

  if (permission === PERMISSIONS.MANAGE_ACTIVITIES) {
    return clubAccess.some(access => access.isManager)
  }

  if (permission === PERMISSIONS.VIEW_FINANCE) {
    return clubAccess.some(access => access.isManager || access.isTreasurer)
  }

  if (permission === PERMISSIONS.MANAGE_FINANCE) {
    return clubAccess.some(access => access.isTreasurer)
  }

  if (permission === PERMISSIONS.PARTICIPATE_IN_ACTIVITIES) {
    return clubAccess.some(access =>
      access.isApprovedMember || access.isManager || access.isTreasurer,
    )
  }

  return false
}
